import Head from 'next/head'
import Feature from '../components/Feature'
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Feature
				featureTitle='Explore'
				featureHeadline='Find tennis courts and check their availability'
				featureDescription='Save time by planning to visit parks with the shortest wait time and have easy access to all available court options in your community.'
				featureImg='/images/image-explore.png'
			/>
			<Feature
				featureTitle='Play'
				featureHeadline='Join or queue at a court and track your play time'
				featureDescription='Simplify the use and sharing of courts by organizing players in a queue system—and don’t lose sight of your place in line with notifications!'
				featureImg='/images/image-play.png'
			/>
			<Feature
				featureTitle='Match'
				featureHeadline='Set your preferences and pair up with a player'
				featureDescription='Cut down on communication and have a glance at other users’ looking for someone to play based on your preferences.'
				featureImg='/images/image-match.png'
			/>
		</div>
	)
}
